# Default configuration for Diffusion Thought Tensor Model

model:
  name: "DiffusionThoughtModel"
  embed_dim: 768
  num_layers: 12
  num_heads: 12
  vocab_size: 50257  # GPT-2 vocabulary
  max_seq_length: 256
  dropout: 0.1
  
thought_tensor:
  input_dims: [32, 32, 16]  # 3D tensor
  output_dims: [32, 32, 8]   # Compressed output
  hidden_dim: 512
  compression_ratio: 0.75
  
diffusion:
  num_steps: 500
  noise_schedule: "sqrt"
  beta_start: 0.0001
  beta_end: 0.02
  
training:
  batch_size: 4
  gradient_accumulation_steps: 8
  learning_rate: 1e-4
  warmup_steps: 5000
  total_steps: 100000
  eval_every: 1000
  save_every: 5000
  
optimizer:
  type: "AdamW"
  weight_decay: 0.01
  betas: [0.9, 0.999]
  eps: 1e-8
  
hardware:
  device: "cuda"
  mixed_precision: true
  gradient_checkpointing: true
  num_workers: 4
